In [42]:
import numpy as np

In [43]:
import pandas as pd

In [ ]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Arcite\Downloads\house-prices (3).csv")
df

In [48]:
type(df.iloc[0])

pandas.Series

In [ ]:
check type

In [ ]:
select data

In [49]:
type(df.iloc[[0]])

pandas.DataFrame

In [ ]:
type of row 0

 pandas Series.

In [51]:
df.iloc[:3]

   Home   Price  SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood
0     1  114300  1790         2          2       2    No         East
1     2  114200  2030         4          2       3    No         East
2     3  114800  1740         3          2       1    No         East

3rd last row

first 3 rows of the DataFrame

In [22]:
df.iloc[lambda x: x.index % 2 == 0]

     Home   Price  SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood
0       1  114300  1790         2          2       2    No         East
2       3  114800  1740         3          2       1    No         East
4       5  119800  2130         3          3       3    No         East
6       7  151600  1830         3          3       3   Yes         West
8       9  119200  2110         4          2       3    No         East
..    ...     ...   ...       ...        ...     ...   ...          ...
118   119  150200  1950         3          2       3   Yes        North
120   121  110400  1930         2          3       3    No        North
122   123  144800  2060         2          2       1   Yes         East
124   125  147900  2160         4          3       3   Yes         East
126   127  149900  2020         3          3       1    No         West

[64 rows x 8 columns]

Selects rows whose index values are even

In [23]:
df.iloc[0, 1]

np.int64(114300)

In [24]:
df.iloc[[0, 2], [1, 3]]

    Price  Bedrooms
0  114300         2
2  114800         3

In [ ]:
row_position, column_position]

selected rows& coloum

In [25]:
df.iloc[1:3, 0:3]

   Home   Price  SqFt
1     2  114200  2030
2     3  114800  1740

In [27]:
df.iloc[:, lambda df: [0, 2]]

     Home  SqFt
0       1  1790
1       2  2030
2       3  1740
3       4  1980
4       5  2130
..    ...   ...
123   124  1900
124   125  2160
125   126  2070
126   127  2020
127   128  2250

[128 rows x 2 columns]

selecting using funtion

In [29]:
df.loc[df["Price"] > 6]

     Home   Price  SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood
0       1  114300  1790         2          2       2    No         East
1       2  114200  2030         4          2       3    No         East
2       3  114800  1740         3          2       1    No         East
3       4   94700  1980         3          2       3    No         East
4       5  119800  2130         3          3       3    No         East
..    ...     ...   ...       ...        ...     ...   ...          ...
123   124  119700  1900         3          3       3   Yes         East
124   125  147900  2160         4          3       3   Yes         East
125   126  113500  2070         2          2       2    No        North
126   127  149900  2020         3          3       1    No         West
127   128  124600  2250         3          3       4    No        North

[128 rows x 8 columns]

In [31]:
df.loc[df["SqFt"] > 6, ["Price"]]

      Price
0    114300
1    114200
2    114800
3     94700
4    119800
..      ...
123  119700
124  147900
125  113500
126  149900
127  124600

[128 rows x 1 columns]

In [34]:
df.loc[(df["Price"] > 1) & (df["SqFt"] < 8)]

Empty DataFrame
Columns: [Home, Price, SqFt, Bedrooms, Bathrooms, Offers, Brick, Neighborhood]
Index: []

Select rows where Price > 1 AND SqFt < 8.

In [35]:
df.loc[(df["SqFt"] > 4) | (df["Price"] < 5)]

     Home   Price  SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood
0       1  114300  1790         2          2       2    No         East
1       2  114200  2030         4          2       3    No         East
2       3  114800  1740         3          2       1    No         East
3       4   94700  1980         3          2       3    No         East
4       5  119800  2130         3          3       3    No         East
..    ...     ...   ...       ...        ...     ...   ...          ...
123   124  119700  1900         3          3       3   Yes         East
124   125  147900  2160         4          3       3   Yes         East
125   126  113500  2070         2          2       2    No        North
126   127  149900  2020         3          3       1    No         West
127   128  124600  2250         3          3       4    No        North

[128 rows x 8 columns]

In [37]:
type(df.iloc[0])

pandas.Series

In [38]:
df.iloc[lambda x: x.index % 2 == 0]

     Home   Price  SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood
0       1  114300  1790         2          2       2    No         East
2       3  114800  1740         3          2       1    No         East
4       5  119800  2130         3          3       3    No         East
6       7  151600  1830         3          3       3   Yes         West
8       9  119200  2110         4          2       3    No         East
..    ...     ...   ...       ...        ...     ...   ...          ...
118   119  150200  1950         3          2       3   Yes        North
120   121  110400  1930         2          3       3    No        North
122   123  144800  2060         2          2       1   Yes         East
124   125  147900  2160         4          3       3   Yes         East
126   127  149900  2020         3          3       1    No         West

[64 rows x 8 columns]

ven-indexed rows

In [39]:
df.iloc[1:4, 0:3]

   Home   Price  SqFt
1     2  114200  2030
2     3  114800  1740
3     4   94700  1980

integer location / positional indexing

In [40]:
df.iloc[1:126, 0:125]

     Home   Price  SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood
1       2  114200  2030         4          2       3    No         East
2       3  114800  1740         3          2       1    No         East
3       4   94700  1980         3          2       3    No         East
4       5  119800  2130         3          3       3    No         East
5       6  114600  1780         3          2       2    No        North
..    ...     ...   ...       ...        ...     ...   ...          ...
121   122  105600  1930         3          3       3    No         East
122   123  144800  2060         2          2       1   Yes         East
123   124  119700  1900         3          3       3   Yes         East
124   125  147900  2160         4          3       3   Yes         East
125   126  113500  2070         2          2       2    No        North

[125 rows x 8 columns]

In [41]:
df.iloc[1:120, 0:100]

     Home   Price  SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood
1       2  114200  2030         4          2       3    No         East
2       3  114800  1740         3          2       1    No         East
3       4   94700  1980         3          2       3    No         East
4       5  119800  2130         3          3       3    No         East
5       6  114600  1780         3          2       2    No        North
..    ...     ...   ...       ...        ...     ...   ...          ...
115   116  102500  1900         3          3       3    No        North
116   117  199500  2290         5          4       1   Yes         West
117   118  117800  1920         3          2       2    No        North
118   119  150200  1950         3          2       3   Yes        North
119   120  109700  1920         2          2       4    No        North

[119 rows x 8 columns]

Select 119 rows and 100 columns.